/*
  请求url统一配置
 */
// 登陆
export const login = 'admin/login'
// 退出
export const singout = 'admin/singout'

// TODO ...
// 区域默认实体
export const getEntityByRegionCode = 'entity/getEntityByRegionCode'
export const saveEntity = 'entity/saveEntity'
export const searchAllRegion = 'entity/searchAllRegion'
export const searchAllEntity = 'entity/searchAllEntity'

// 子库最大发运量
export const maximumShippGetSearchCond = 'maximumShipp/getMainAndSubHouse'
export const maximumShippSearch = 'maximumShipp/search'
export const maximumShippDelData = 'maximumShipp/remove'
export const maximumShippSearchData = 'maximumShipp/searchData'
export const maximumShippSave = 'maximumShipp/save'
// 预计入库量
export const searchSchedule = 'scheduledReceipt/searchData'
export const deleteSchedule = 'scheduledReceipt/removeSchedu'
export const saveSchedule = 'scheduledReceipt/save'
// 订单类型
export const orderTypeSearch = 'orderType/search'
export const orderTypeRemove = 'orderType/remove'
export const orderTypeSave = 'orderType/save'
// DMS订单类型与ERP订单类型匹配
export const dmsERPgetSearchCond = 'orderTypeMatchErp/getSearchCond'
export const dmsERPsearch = 'orderTypeMatchErp/search'
export const dmsERPSave = 'orderTypeMatchErp/save'
export const dmsERPRemove = 'orderTypeMatchErp/remove'
// 经销商出货-提报时效
export const subTimeGetSeaCond = 'dealerShipmentsSubmitTimelinessManage/getSearchCond'
export const subTimeSearch = 'dealerShipmentsSubmitTimelinessManage/search'
export const subTimeSave = 'dealerShipmentsSubmitTimelinessManage/save'
// 二级提货商库存提报时效
export const subInvTimeSearch = 'secondDealerInventorySubmitTimeliness/search'
export const subInvTimeSave = 'secondDealerInventorySubmitTimeliness/save'
// 库存盘点时效规则
export const invSubTimegetSearchCond = 'dealerInventorySubmitTimeliness/getSearchCond'
export const invSubTimeSearch = 'dealerInventorySubmitTimeliness/search'
export const invSubTimeSave = 'dealerInventorySubmitTimeliness/save'
/* 后台配置->订单配置->事物状态配置 transStatusConfig */
export const transStatusConfigGetCondition = 'transactionConfig/getTransactionType'
export const transStatusConfigSearch = 'transactionConfig/search'
export const transStatusConfigSave = 'transactionConfig/addAndUpdate'
/* 后台配置->订单配置->订单起订量配置 minOrderQuantityConfig */
export const minOrderQuantityConfigGetCondition = 'minOrderQuantityConfig/getSearchCondition'
export const minOrderQuantityConfigSearch = 'minOrderQuantityConfig/search'
export const minOrderQuantityConfigSave = 'minOrderQuantityConfig/save'
export const minOrderQuantityConfigDelete = 'minOrderQuantityConfig/delete'
/* 后台配置->订单配置->一级订单编号规则 firstDealerOrderRule */
export const firstDealerOrderSearch = 'firstDealerOrderRule/getFirstDealerOrderRule'
export const firstDealerOrderDisable = 'firstDealerOrderRule/updateModel'
export const firstDealerOrderSearchCond = 'firstDealerOrderRule/getSearchCond'
export const firstDealerOrderAdd = 'firstDealerOrderRule/addAndUpdate'
/* 后台配置->订单配置->其他订单编号规则 otherOrderRule */
export const otherOrderRuleGetOtherOrderRule = 'otherOrderRule/getOtherOrderRule'
export const otherOrderDisable = 'otherOrderRule/updateModel'
export const otherOrderSearchCond = 'otherOrderRule/getSearchCond'
export const otherOrderAdd = 'otherOrderRule/addAndUpdate'
/* 后台配置->进销存配置->批次规则 batchRuleConfig */
export const batchRuleConfigSearchBathRule = 'batchRule/searchBathRule'
export const batchRuleConfigGetAllType = 'batchRule/getAllType'
export const batchRuleConfigSaveBathRule = 'batchRule/saveBathRule'
export const batchRuleConfigDeleteBathRule = 'batchRule/deleteBathRule'
/* 后台配置->进销存配置->零散客户维护 scatteredCustomerConfig */
export const scatteredCustomerConfigSearchScatCustomer = 'scatteredCustomer/searchScatCustomer'
export const scatteredCustomerConfigGetAllType = 'scatteredCustomer/getAllType'
export const scatteredCustomerConfigSaveScatCustomer = 'scatteredCustomer/saveScatCustomer'
export const scatteredCustomerConfigDeleteScatCustomer = 'scatteredCustomer/deleteScatCustomer'
/* 后台配置->订单配置->需求到货日期 */
export const getEntity = 'demandDate/getEntityByRegionCode'
export const addOrUpdateEntity = 'demandDate/addOrUpdateEntity'
export const removeEntity = 'demandDate/removeEntity'
/* 进销存管理 -> 入库管理 -> 收货确认 */
export const receiptConfirmationGetReceiptConfirmationPreCondition = 'receiptConfirmation/getReceiptConfirmationPreCondition'
export const receiptConfirmationFindReceiptConfirmationList = 'receiptConfirmation/findReceiptConfirmationList'
export const receiptConfirmationFindReceiptConfirmationDetail = 'receiptConfirmation/findReceiptConfirmationDetail'
export const receiptConfirmationSaveReceiptConfirmation = 'receiptConfirmation/saveReceiptConfirmation'
/* 客户弹窗 */
export const customerGetCondition = 'customer/getSearchCondition'
export const customerSearch = 'customer/search'
// 代收运费
export const collectFreightGetSearchCond = 'collectFreight/getSearchCond'
export const collectFreightSearch = 'collectFreight/searchData'
export const collectFreightSave = 'collectFreight/save'
export const deleteCollect = 'collectFreight/remove'
export const exportCollect = 'collectFreight/export'
export const importCollect = 'collectFreight/import'
export const invalidCollect = 'collectFreight/invalid'
/* 产品弹窗 */
export const productSearchProdInfo = 'productSelect/searchProdInfo'
export const productGetAllType = 'productSelect/getAllType'
export const productIsCollection = 'productSelect/isCollection'
/* 后台配置->订单配置->品类子项配置 SubCategoryConfig */
export const subCategoryConfigGetPreCondintion = 'subCategoryConfig/getPreCondintion'
export const subCategoryConfigGetSubCategoryList = 'subCategoryConfig/getSubCategoryList'
export const subCategoryConfigSaveSubCategoryList = 'subCategoryConfig/saveSubCategoryList'
export const subCategoryConfigRemoveSubCategoryList = 'subCategoryConfig/removeSubCategoryList'
export const subCategoryConfigUploadImg = '/subCategoryConfig/uploadImg'
/* 价格维护查询 */
export const priceMaintainInit = 'priceMaintainC/init'
export const priceMaintainSearch = 'priceMaintainC/priceMaintainSearch'
export const priceMaintainLost = 'priceMaintainC/priceMaintainLose'
export const priceMaintainDelete = 'priceMaintainC/priceMaintainDelete'
export const priceMaintainRelease = 'priceMaintainC/priceMaintainRelease'
export const priceMaintainExport = 'priceMaintainC/priceMaintainExport'
export const priceMaintainAllRelease = 'priceMaintainC/priceMaintainAllRelease'
/* 核销明细维护 */
export const costReturnCheckGetCstChkRetList = 'costReturnCheck/getCstChkRetList'
export const costReturnCheckDeteleCostReturnCheck = 'costReturnCheck/deteleCostReturnCheck'
export const costReturnCheckSaveCostReturnCheckList = 'costReturnCheck/saveCostReturnCheckList'
export const costReturnCheckReleaseCostReturnCheck = 'costReturnCheck/releaseCostReturnCheck'
export const costReturnCheckExportCostReturnCheck = 'costReturnCheck/exportCostReturnCheck'
/* 时效提报配置 */
export const planSubmitTimeInit = 'planSubmitTimeC/init'
export const planSubmitTimeSearch = 'planSubmitTimeC/planSubmitSearch'
export const planSubmitTimeSave = 'planSubmitTimeC/planSubmitTimeSave'
/* 均衡出货配置 */
export const banlancedShipmentInit = '/balancedShipmentC/init'
export const banlanceShipmentSearch = '/balancedShipmentC/balancedShipmentSearch'
export const banlanceShipmentSave = '/balancedShipmentC/balancedShipmentSave'
/* 订单查询 */
export const ordergetSearchCond = 'orderHeader/getSearchCond'
export const orderSearch = 'orderHeader/search'
export const orderHeadGetTime = 'orderHeader/getTime'
export const orderExport = 'orderHeader/export'
export const orderBatchSubmit = 'orderHeader/batchSubmit'
export const orderHeadGetStatus = 'orderHeader/getOrderStatus'
/* 价格创建 */
export const priceMaintainCreateInit = 'priceMaintainCreateC/priceMaintainCreateInit'
export const priceMaintainCreateSave = 'priceMaintainCreateC/priceMaintainCreateSave'
export const priceMaintainCreateImport = 'priceMaintainCreateC/importExcel'
export const priceMaintainCreatePriceList = 'priceMaintainCreateC/priceMaintainCreatePriceList'
export const priceMaintainCreateModeExport = 'priceMaintainCreateC/priceMaintainCreateModeExport'
/* 后台配置->订单配置->借货方信息配置 LenderInfoConfig */
export const lenderInfoConfigGetOrganInfo = 'lenderInfo/getOrganInfo'
export const lenderInfoConfigGetLenderInfoList = 'lenderInfo/getLenderInfoList'
export const lenderInfoConfigSaveLenderInfo = 'lenderInfo/saveLenderInfo'
/* 计划管理->任务管理->内部任务管理->任务查询 */
export const taskSearchInitData = 'taskSearch/initData'
export const taskSearchSearchTask = 'taskSearch/searchTask'
export const taskExport = 'taskSearch/export'
export const taskDownload = 'taskSearch/download'
export const taskuploadData = 'taskSearch/uploadData'
export const taskSaveTask = 'taskSearch/saveTask'
/* 计划管理->任务管理->渠道商任务管理->任务查询 */
export const channelTaskInitData = 'channelSearch/initChannelData'
export const channelTaskSearch = 'channelSearch/searchChannelTask'
export const channelTaskExport = 'channelSearch/exportChannel'
export const channelTaskDownload = 'channelSearch/downloadChannel'
export const channelTaskUpload = 'channelSearch/uploadDataChannel'
export const channelTaskSave = 'channelSearch/saveChannelTask'
/* 计划管理->月目标设置 */
export const monthTargetInit = 'monthTarget/initSearchData'
export const monthTargetSearch = 'monthTarget/searchMonthTarget'
export const monthTargetSave = 'monthTarget/saveMonthTarget'
/* 计划管理->三月九旬计划提报 */
export const threeNineInit = 'threeNine/initSearchData'
export const threeNineSearch = 'threeNine/searchData'
export const threeNineCalc = 'threeNine/calculateData'
export const threeNineSave = 'threeNine/saveData'
/* 计划管理->三月九旬计划审核 */
export const threeNineCheckInit = 'threeNineCheck/initData'
export const threeNineCheckSearch = 'threeNineCheck/searchCheckData'
export const threeNineCheckExport = 'threeNineCheck/exportCheckData'
export const threeNineCheckSave = 'threeNineCheck/saveCheckData'
/* 计划执行跟踪 */
export const planTrackSearch = 'planTrack/searchData'
export const planTrackExport = 'planTrack/export'

// 客户基本信息查询
export const customerInfoGetSearchCond = 'customerBaseInfo/getSearchCond'
export const customerInfoSearch = 'customerBaseInfo/search'
export const customerInfoExport = 'customerBaseInfo/export'

/* 排单管理->分批发货拆单 */
export const batchShipSplitOrderGetSearchCondition = 'batchShipSplitOrder/getSearchCondition'
export const batchShipSplitOrderSearch = 'batchShipSplitOrder/search'
export const batchShipSplitOrderCancelNotSchedual = 'batchShipSplitOrder/cancelNotSchedual'
export const batchShipSplitOrderConfim = 'batchShipSplitOrder/confim'

/* 导入模板下载 */
export const excelTemplateExportTemplate = 'excelTemplate/exportImportTemplate'
/* 费用返还查询 */
export const costReturnInit = 'costReturnSearchC/costReturnSearchInit'
export const costReturnSearch = 'costReturnSearchC/costReturnSearchSearch'
export const costReturnExport = 'costReturnSearchC/costReturnExport'
export const costReturnLose = 'costReturnSearchC/costReturnLose'
export const costReturnDelete = 'costReturnSearchC/costReturnDelete'
export const costReturnRelease = 'costReturnSearchC/costReturnRelease'
export const costReturnAllRelease = 'costReturnSearchC/costReturnAllRelease'
/* 费用返还创建 */
export const costReturnCreateInit = 'costReturnCreateC/costReturnCreateInit'
export const costReturnCreateImport = 'costReturnCreateC/costReturnCreateImport'
export const costReturnCreateGetBusinessEntity = 'costReturnCreateC/costReturnCreateGetBusinessEntity'
export const costReturnModeExport = 'costReturnCreateC/costReturnModeExport'
export const costReturnModeSave = 'costReturnCreateC/costReturnModeSave'
// 提货商库存查询
export const inventoryQueryGetSearchCond = 'inventoryQuery/getSearchCond'
export const inventoryQueryHanded = 'inventoryQuery/searchSecondHanded'
export const inventoryQueryUnhanded = 'inventoryQuery/searchSecondUnhanded'
export const inventoryQueryFirst = 'inventoryQuery/searchFirstInventory'
export const inventoryQueryFirstDetail = 'inventoryQuery/searchInvDetail'
export const inventoryQueryFirstExport = 'inventoryQuery/firstExport'
export const inventoryQuerySecondExport = 'inventoryQuery/secondExport'
export const costReturnCreateSave = 'costReturnCreateC/costReturnCreateSave'
/* 库存盘点与确认 */
export const inventorySearchAndConfirmInit = 'inventorySearchAndConfirmC/inventorySearchAndConfirmInit'
export const inventorySearchAndConfirmSearch = 'inventorySearchAndConfirmC/inventorySearchAndConfirmSearch'
export const inventorySearchAndConfirmDetailsInit = 'inventorySearchAndConfirmC/inventorySearchAndConfirmDetailsInit'
export const inventorySearchAndConfirmConfirm = 'inventorySearchAndConfirmC/inventorySearchAndConfirmConfirm'
/* 排单管理->选单预排 */
export const preparedSchedualOrderGetSearchCondition = 'preparedSchOrd/getSearchCondition'
export const preparedSchedualOrderSearch = 'preparedSchOrd/search'
export const preparedSchedualOrderConfim = 'preparedSchOrd/confim'
export const preparedSchedualOrderCancel = 'preparedSchOrd/cancel'
/* 排单管理->排单主界面 */
export const schedualOrderInitData = 'schedualOrder/initData'
export const schedualOrderQueryToBeComfirm = 'schedualOrder/queryToBeComfirm'
export const schedualOrderCommit = 'schedualOrder/commit'
export const schedualOrderQueryWarehouseData = 'schedualOrder/queryWarehouseData'
export const schedualOrderQueryDetail = 'schedualOrder/querySchOrdDetail'
export const schedualOrderCommitConfimQuantity = 'schedualOrder/commitConfimQuantity'
export const schedualOrderQueryToBeChangeWareHouseData = 'schedualOrder/queryToBeChangeWareHouseData'
export const schedualOrderChangeWareHouseDataCommit = 'schedualOrder/commitChangeWareHouse'
export const schedualOrderQueryToBeChangeCarrierData = 'schedualOrder/queryToBeChangeCarrierData'
export const schedualOrderChangeCarrieAndShipMethCommit = 'schedualOrder/commitChangeCarrieShipMeth'
export const schedualOrderQueryFreightData = 'schedualOrder/queryFreightData'
export const schedualOrderFreightCommit = 'schedualOrder/freightCommit'
export const schedualOrderDetailExport = 'schedualOrder/export'
/* 订单管理-> 产品选择 */
export const orderProductSelectProductSelect = 'orderProductSelect/productSelect'
export const orderProductSelectFavSave = 'orderProductSelect/favSave'
/* 订单管理-> 借货单、调拨单 */
export const adjLendOrderSaveLendOrder = 'adjLendOrder/saveLendOrder'
export const adjLendOrderSaveAdjOrder = 'adjLendOrder/saveAdjOrder'
export const adjLendOrderGetAddressOfficeList = 'adjLendOrder/getAddressOfficeList'
export const adjLendOrderSearchLendOrder = 'adjLendOrder/searchLendOrder'
export const adjLendOrderGetLendOrderSearchPreBean = 'adjLendOrder/getLendOrderSearchPreBean'
export const adjLendOrderGetAdjustOrderSearchPreBean = 'adjLendOrder/getAdjustOrderSearchPreBean'
export const adjLendOrderSearchAdjustOrder = 'adjLendOrder/searchAdjustOrder'
export const adjLendOrderGetAdjustOrderDetail = 'adjLendOrder/getAdjustOrderDetail'
export const adjLendOrderGetLendOrderDetail = 'adjLendOrder/getLendOrderDetail'
export const adjLendOrderAbolishAdjustOrder = 'adjLendOrder/abolishAdjustOrder'
export const adjLendOrderAbolishLendOrder = 'adjLendOrder/abolishLendOrder'
export const adjLendOrderSaveReturnOrderLine = 'adjLendOrder/saveReturnOrderLine'
export const adjLendOrderSaveLendOrderRemarks = 'adjLendOrder/saveLendOrderRemarks'
export const adjLendOrderSaveReturnGoodsRemarks = 'adjLendOrder/saveReturnGoodsRemarks'
export const adjLendOrderGetReturnGoodsRemarks = 'adjLendOrder/getReturnGoodsRemarks'
export const adjLendOrderGetLendOrderReport = 'adjLendOrder/getLendOrderReport'
export const adjLendOrderExportLendOrderReport = 'adjLendOrder/exportLendOrderReport'
export const adjLendOrderGetCurrentTime = 'adjLendOrder/getCurrentTime'
//* 经销商月度任务达成分析报表*
export const monthTargetReportGetPreCondition = 'monthTargetReport/getPreCondition'
export const monthTargetReportGetMonthSummary = 'monthTargetReport/getMonthSummary'
export const monthTargetReportExportMonthTargetReport = 'monthTargetReport/exportMonthTargetReport'
/* 销量汇总 */
export const salesCollectInit = 'salesCollectC/salesCollectInit'
export const salesCollectSearch = 'salesCollectC/salesCollectSearch'
export const salesCollectExport = 'salesCollectC/salesCollectExport'
/* 订单管理->下单界面 */
export const dealerOrderInit = 'dealerOrder/init'
export const dealerOrderInitRemark = 'dealerOrder/initRemark'
export const dealerOrderSaveRemark = 'dealerOrder/saveRemark'
export const dealerSaveOrder = 'dealerOrder/saveOrder'
export const dealerCopyOrder = 'dealerOrder/copyOrder'
export const dealerCancelOrder = 'dealerOrder/cancelOrder'
export const dealerGetStartWeight = 'dealerOrder/getStartWeight'
export const dealerOrderDetailGetOrderDetail = 'dealerOrderDetail/getOrderDetail'
export const dealerOrderDemandChange = 'dealerOrderDetail/dealerOrderDemandChange'
export const dealerOrderCloseOrder = 'dealerOrder/closeOrder'
export const dealerOrderDeleteRemark = 'dealerOrder/deleteRemark'
/* 订单管理->库存盘点查询及确认  */
export const orderDemandTimeExamineInit = 'orderDemandTimeExamineC/orderDemandTimeExamineInit'
export const orderDemandTimeExamineSearch = 'orderDemandTimeExamineC/orderDemandTimeExamineSearch'
export const orderDemandTimeExamineAgree = 'orderDemandTimeExamineC/orderDemandTimeExamineAgree'
export const orderDemandTimeExamineRefuse = 'orderDemandTimeExamineC/orderDemandTimeExamineRefuse'

/* 此文件为公共部分，冲突时别把develop部分给删了！把冲突的分割线去掉就好！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！ */

// 报表管理->排单报表->排单报表
export const scheduleOrderReportSearch = 'scheduleOrderReport/search'
export const scheduleOrderReportGetSearchCond = 'scheduleOrderReport/getSearchCond'
export const scheduleOrderReportExport = 'scheduleOrderReport/export'
// 报表管理  ->报表管理 -> 出货明细报表
export const shippmentDetailReportSearch = 'shippmentDetailReport/search'
export const shippmentDetailReportExport = 'shippmentDetailReport/export'
// 排单管理 -> 排单查询
export const schedualOrderSearchInit = 'rowOrderSearch/initData'
export const schedualOrderSearchSearchData = 'rowOrderSearch/search'
export const schedualOrderSearchExport = 'rowOrderSearch/export'
export const schedualOrderSearchRepeal = 'rowOrderSearch/repeal'
export const schedualOrderSearchResubmit = 'rowOrderSearch/resubmit'
// 帮助中心
export const helperCenterInit = 'helperCenter/initData'
export const helperCenterSearch = 'helperCenter/searchData'
export const helperCenterGet = 'helperCenter/getOneData'
export const helperCenterSave = 'helperCenter/saveData'
export const helperCenterDelete = 'helperCenter/deleteData'
export const helperCenterUpdateIndex = 'helperCenter/changeIndex'
// 用户基本信息
export const userBaseInfoGetSearchCond = 'userBaseInfo/getSearchCond'
export const userBaseInfoSaveBusinessPhone = 'userBaseInfo/saveBusinessPhone'
export const userBaseInfoUnbindBusinessPhone = 'userBaseInfo/unbindBusinessPhone'
export const userBaseInfoSave = 'userBaseInfo/save'
// 图片管理
export const imageManageInit = 'imageManageC/imageManageInit'
export const imageManageSearch = 'imageManageC/imageManageSearch'
export const imageManageUpload = 'imageManageC/imageManageUpload'
export const imageManageSave = 'imageManageC/imageManageSave'
export const imageManageEdit = 'imageManageC/imageManageEdit'
export const imageManageDelete = 'imageManageC/imageManageDelete'
// 经销商首页
export const OUHomePageInit = 'homePageC/OUHomePageInit'
export const OUHomePageGetContent = 'homePageC/OUHomePageGetContent'
// 咨询信息
export const infoMessInit = 'infoMess/initData'
export const infoMessSave = 'infoMess/saveData'
export const infoMessSearch = 'infoMess/searchData'
export const infoMessGetOne = 'infoMess/getOneData'
export const infoMessDelete = 'infoMess/deleteData'
// 装运搜索
export const shippingSearchInit = 'shippingSearchC/shippingSearchInit'
export const shippingSearchSearch = 'shippingSearchC/shippingSearchSearch'
export const shippingSearchDialogInit = 'shippingSearchC/shippingSearchDialogInit'
export const shippingSearchConfirm = 'shippingSearchC/shippingSearchConfirm'
export const shippingSearchAllConfimr = 'shippingSearchC/shippingSearchAllConfimr'
export const shippingSearchAllCount = 'shippingSearchC/shippingSearchAllCount'
// 经销商库存调整
export const invManagerTypeAndStatus = 'invManager/getTypesAndStatus'
export const searchTotalInvManager = 'invManager/searchTotalInvManager'
export const queryShipCusProductBatchInfo = 'invManager/queryShipCusProductBatchInfo'
export const saveNewInvMnager = 'invManager/saveNewInvMnager'
export const commitNewInv = 'invManager/commitNewInv'
export const searchInvDetail = 'invManager/searchInvDetail'
export const deleteNewInvDetail = 'invManager/deleteNewInvDetail'
export const updateInvDetail = 'invManager/updateInvDetail'
export const commitDetailInv = 'invManager/commitDetailInv'
export const searchStartInv = 'invManager/searchStartInv'
export const saveStartInv = 'invManager/saveStartInv'
export const commitStartInv = 'invManager/commitStartInv'
export const importStartInv = 'invManager/importStartInv'
// 下游订单处理
export const searchDownstreamOrder = 'downStreamOrder/searchDownstreamOrder'
export const exportDownStreamOrder = 'downStreamOrder/exportDownStreamOrder'
export const allSend = 'downStreamOrder/allSend'
export const allYibaoSend = 'downStreamOrder/allYibaoSend'
export const orderGetTypesAndStatus = 'downStreamOrder/getTypesAndStatus'
export const sendPro = 'downStreamOrder/sendPro'
export const yibaoSend = 'downStreamOrder/yibaoSend'
export const saveEntityAndConfirm = 'downStreamOrder/saveEntityAndConfirm'
export const searchDeailByOrderNum = 'downStreamOrder/searchDeailByOrderNum'
export const judeHasRelationship = 'downStreamOrder/judeHasRelationship'
export const getCusEntity = 'promotion/getCusEntity'
export const closeOrder = 'downStreamOrder/closeOrder'
export const getSelectCus = 'downStreamOrder/getSelectCus'
export const getTime = 'downStreamOrder/getTime'
// 促销管理
export const seachPromotionHead = 'promotion/seachPromotionHead'
export const getCusOrg = 'promotion/getCusOrg'
export const closePro = 'promotion/closePro'
export const removeHead = 'promotion/removeHead'
export const saveProHead = 'promotion/saveProHead'
export const removeOne = 'promotion/removeOne'
export const removeTwo = 'promotion/removeTwo'
export const saveOneChannel = 'promotion/saveOneChannel'
export const saveTwoChannel = 'promotion/saveTwoChannel'
export const selectReleaseOne = 'promotion/selectReleaseOne'
export const allReleaseOne = 'promotion/allReleaseOne'
export const allReleaseTwo = 'promotion/allReleaseTwo'
export const failOne = 'promotion/failOne'
export const failTwo = 'promotion/failTwo'
export const exportOneChannel = 'promotion/exportOneChannel'
export const seachOneChannel = 'promotion/seachOneChannel'
export const seachTwoChannel = 'promotion/seachTwoChannel'
// 费用核算台账查询
export const searchCost = 'costAccount/search'
export const exportCost = 'costAccount/exportData'
// 用户密码修改
export const userModifyPasswordToCreate = 'userModifyPassword/getSearchCond'
export const userModifyPasswordToCheck = 'userModifyPassword/checkPassword'
/* 后台管理->数据对比 */
export const databaseCompareGetSearchCond = 'databaseCompare/getSearchCond'
export const databaseCompareSearch = 'databaseCompare/search'
// 库存盘点提报查询
export const inventoryReportSearchInint = 'inventoryReportSearchController/inventoryReportSearchInint'
export const inventoryReportSearchSearch = 'inventoryReportSearchController/inventoryReportSearchSearch'
export const inventoryReportSearchExport = 'inventoryReportSearchController/export'
export const userModifyPasswordToUpdate = 'userModifyPassword/updatePassword'
// 进销存管理 -》 经销商出货明细查询
export const shipmentSearchInitData = 'shipmentSearch/initData'
export const shipmentSearchSearch = 'shipmentSearch/search'
export const shipmentSearchExport = 'shipmentSearch/export'
export const shipmentSearchSearchPromtion = 'shipmentSearch/searchPromtion'
export const shipmentSearchSearchReceiveCustomer = 'shipmentSearch/searchReceiveCustomer'
// 进销存管理 -》 流水查询
export const shipmentFlowInitData = 'shipmentFlow/initData'
export const shipmentFlowSearchData = 'shipmentFlow/search'
export const shipmentFlowExport = 'shipmentFlow/export'
// 促销维护
export const promotionSearchPromotionHead = 'promotion/seachPromotionHead'
// 装运单查询
export const shipListSearchInit = 'shipListSearchC/shipListSearchInit'
export const shipListSearchSearch = 'shipListSearchC/shipListSearchSearch'
export const shipListSearchDetail = 'shipListSearchC/shipListSearchDetail'
export const shipListSearchNotice = 'shipListSearchC/shipListSearchNotice'
export const shipListSearchCancel = 'shipListSearchC/shipListSearchCancel'
// 装运报表
export const shippingReportInit = 'shippingReportC/shippingReportInit'
export const shippingReportSearch = 'shippingReportC/shippingReportSearch'
export const shippingReportExport = 'shippingReportC/shippingReportExport'
// 进销存管理 -》 出货提报
export const shipmentSubmitInitData = 'shipment/initData'
export const shipmentSubmitSearchShipHeaderData = 'shipment/searchShipHeaderData'
export const shipmentSubmitSearchShipDetail = 'shipment/searchShipDetail'
export const shipmentSubmitSearchCanUsePromotion = 'shipment/queryCanUseProm'
export const shipmentSubmitOutStoreConfirm = 'shipment/outStoreConfirm'
export const shipmentSubmitInitScatteredShipData = 'shipment/initScatteredShipData'
export const searchScattAddressInfo = 'shipment/searchScattAddressInfo'
export const deleteScattAddressInfo = 'shipment/deleteScattAddressInfo'
export const confirmScattAddressInfo = 'shipment/confirmScattAddressInfo'
export const repealOutStore = 'shipment/repealOutStore'
export const shipmentExportData = 'shipment/export'
export const shipmetnScatteredExportData = 'shipment/scatteredExport'
export const shipmentQueryProductPrice = 'shipment/queryProductPrice'
export const getShipDetailPrintMag = 'shipment/getPrintMsg'
// 首页菜单
export const innerIndexGetUserMenu = 'innerIndex/getUserMenu'
export const innerIndexGetUserType = 'innerIndex/getUserType'
// 查账对账
export const searchFinance = 'finance/searchFinance'
export const searchFinanceDetail = 'finance/searchFinanceDetail'
export const confirmLetter = 'finance/confirmLetter'
export const exportFinance = 'finance/exportFinance'
// 用户角色管理
export const creatRole = 'role/creatRole'
export const updateRole = 'role/updateRole'
export const searchAllMenu = 'role/searchAllMenu'
export const getCheckedMenu = 'role/getCheckedMenu'
export const deleteRole = 'role/deleteRole'
export const searchRole = 'role/searchRole'
export const searchAllMenuByRole = 'role/searchAllMenuByRole'
export const addUser = 'user/addUser'
export const searchUser = 'user/searchUser'
export const getCheckedMenuOfList = 'role/getCheckedMenuOfList'
export const updatingUser = 'user/updateUser'
export const searchRoleByUserId = 'role/searchRoleByUserId'
export const searchAllMenuByUserRole = 'role/searchAllMenuByUserRole'
export const searchAccount = 'user/searchAccount'
export const getSysTime = 'user/getSysTime'
export const searchShowMenuByUserRole = 'role/searchShowMenuByUserRole'
//* 分销商月度任务达成分析报表*
export const dealerMonthTargetReportGetPreCondition = 'dealerMonthTargetReport/getPreCondition'
export const dealerMonthTargetReportGetMonthSummary = 'dealerMonthTargetReport/getMonthSummary'
// 发货汇总报表
export const deliveryCollectInit = 'deliveryCollectC/deliveryCollectInit'
export const deliveryCollectSearch = 'deliveryCollectC/deliveryCollectSearch'
export const deliveryCollectExport = 'deliveryCollectC/deliveryCollectExport'

export const dealerMonthTargetReportExport = 'dealerMonthTargetReport/exportMonthTargetReport'
//* 组织月度任务达成分析报表*
export const organMonthTargetReportGetPreCondition = 'organMonthTargetReport/getPreCondition'
export const organMonthTargetReportGetOrganMonthSummary = 'organMonthTargetReport/getOrganMonthSummary'
export const organMonthTargetReportExport = 'organMonthTargetReport/export'
// 报表管理  核销（搭赠）报表
export const verificationDetailReportInit = 'verificationDetailReport/initData'
export const verificationDetailReportSearch = 'verificationDetailReport/search'
export const verificationDetailReportExport = 'verificationDetailReport/export'
// 滚动销售预测分析
export const rollingSalesAnalysisGetPreCondition = 'rollingSalesAnalysis/getPreCondition'
export const rollingSalesAnalysisGetRollingSalesAnalysis = 'rollingSalesAnalysis/getRollingSalesAnalysis'
// 安全库存执行分析界面
export const inventoryExecuteAnalysisSearch = 'inventoryExecuteAnalysis/search'
export const inventoryTurnoverDaysSearch = 'inventoryTurnoverDays/search'
